server:
  port: 9500
spring:
  profiles:
    include: monitor
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    sentinel:
#      filter:
#        enabled: false
#      transport:
#        dashboard: localhost:8080
    gateway:
      enabled: true #Gateway开启服务注册和发现的功能
      discovery:
        locator:
          lower-case-service-id: true #请求路径上的服务名配置为小写
      routes:
        # 认证服务
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/auth/**
          filters:
        #            - name: CircuitBreaker
        #              args:
        #                name: authCircuitBreaker
        #                fallbackUri: forward:/fallback/mall-auth
        # 用户服务
        - id: mall-business-system
          uri: lb://mall-business-system
          predicates:
            - Path=/system/**
          filters:

        #            - name: CircuitBreaker
        #              args:
        #                name: authCircuitBreaker
        #                fallbackUri: forward:/fallback/mall-business-user
        # 商品服务
        - id: mall-business-goods
          uri: lb://mall-business-goods
          predicates:
            - Path=/goods/**
          filters:
      default-filters:
        - StripPrefix=1
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: 127.0.0.1:9510
        username: monitor
        password: 123456





