server:
  port: 20080
spring:
  profiles:
    include: monitor
  application:
    name: mall-gateway
  cloud:
    gateway:
      enabled: true #Gateway开启服务注册和发现的功能
      discovery:
        locator:
          lower-case-service-id: true #请求路径上的服务名配置为小写
      routes:
        # 认证服务
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/auth/**
          filters:

        # 用户服务
        - id: mall-business-system
          uri: lb://mall-business-system
          predicates:
            - Path=/system/**
          filters:

        # 商品服务
        - id: mall-business-goods
          uri: lb://mall-business-goods
          predicates:
            - Path=/goods/**
          filters:

        # 设置服务
        - id: mall-business-setting
          uri: lb://mall-business-setting
          predicates:
            - Path=/setting/**
      default-filters:
        - StripPrefix=1
  main:
    allow-bean-definition-overriding: true





