spring:
  profiles:
    include: base
  application:
    name: mall-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true


server:
  port: 9520

