spring:
  profiles:
    include: base
  application:
    name: mall-business-goods
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9610



security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://127.0.0.1:9500/auth/user
