spring:
  profiles:
    include: base,monitor
  application:
    name: mall-business-system
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 1MB #限制文件上传大小为10MB

server:
  port: 9600

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      # http请求
      user-info-uri: http://127.0.0.1:9500/auth/user

# MinIO对象存储相关配置
minio:
  endpoint: http://localhost:9000 #MinIO服务所在地址
  bucketName: mall-cloud #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥