spring:
  profiles:
    include: base
  application:
    name: mall-business-user
  cloud:
    nacos:
      discovery:
        server-addr: ${naocs.url}:8848
  main:
    allow-bean-definition-overriding: true
#dubbo:
#  scan:
#    base-packages: com.emond.mall.business.user.rpc
#  protocol:
#    name: dubbo
#    port: -1
#    serialization:  kryo
#  registry:
#    address: spring-cloud://localhost

server:
  port: 9100

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      # http请求
      user-info-uri: ${auth.url}:9000/auth/user
